### PR TITLE
Friendship 2

### PR DESCRIPTION
**Pull request by MuriloRoque**
In this Milestone, we implemented the mutual friendships for all signed-up users, both on index and show page. We also made tests with RSpec for our new additions and added more styles to our views.

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great job team! :+1: 
Please check on this in a few minutes for some feedback! I wish you the very best and see you at the top :rocket:

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by nikasulo — CHANGES_REQUESTED** [review]
Please consider my comments below towards aligning your project a little more with the requirements!

#### Friendship Model
When friendship is confirmed, an additional row with reversed user-friend pair is created
screenshot

#### Confirmed friendships
We can find user friends only by user_id in friendships table
screenshot

#### Pending friendships
Pending friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
screenshot

#### Friend requests
Friend Requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
screenshot

#### Feed Posts
In order to get all posts written by user on their friends, students can use simple method in User model (in order to NOT do it with Enumerables)
screenshot

**Comment by MuriloRoque** [comment]
We did all of the required changes pointed by the TSE, thank you for the review!

**Review by nikasulo — APPROVED** [review]
# Great work! @MuriloRoque and @Luckyaremu 
Please merge and keep moving forward :+1: I wish you the very best and see you at the top! 

Note: There are a few improvements that could be made to your code and I'm happy to point them out to you. If you are interested, please reach out to me to schedule some time.

I wish you the very best and see you at the top!

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
